import connectionHandler from "./connection.handler.js";
import presenceHandler from "./presence.handler.js";
import roomHandler from "./room.handler.js";
import messageHandler from "./message.handler.js";
import typingHandler from "./typing.handler.js";
import readReceiptHandler from "./readReceipt.handler.js";
import pinningHandler from "./pinning.handler.js";
import laterItemHandler from "./later.handler.js";
import workspaceHandler from "./workspace.handler.js";
import reactionHandler from "./reaction.handler.js";
import callHandler from "./call.handler.js";
import userProfileHandler from "./userProfile.handler.js";
import forwardingHandler from "./forwarding.handler.js";
export const initializeSocketHandlers = (socket, io) => {
  connectionHandler(socket, io);
  presenceHandler(socket, io);
  roomHandler(socket, io);
  messageHandler(socket, io);
  typingHandler(socket, io);
  readReceiptHandler(socket, io);
  pinningHandler(socket, io);
  laterItemHandler(socket, io);
  workspaceHandler(socket, io);
  reactionHandler(socket, io);
  callHandler(socket, io);
  userProfileHandler(socket, io);
  forwardingHandler(socket, io);
};
